### ISSUE TITLE
php_pdo_sqlsrv

### ISSUE THREAD

**Issue by flip111** [maryo/php-5.5-windows-extensions#1]
This extension possibly does not run as is. Because there is no official support from Microsoft for PHP 5.5. Other people have applied a very small patch to make a version for PHP 5.5. See:

http://social.msdn.microsoft.com/Forums/sqlserver/en-US/e1d37219-88a3-46b2-a421-73bfa33fe433/unofficial-php-55-drivers-x86

Microsoft says on the matter (19th june 2014): We are working with PHP to release a new version of the SQL Server PHP driver. We will be able to update the community shortly on a timeframe with it will be released.
Source: http://connect.microsoft.com/SQLServer/feedback/details/790641/sql-server-driver-for-php-5-5

**Comment by maryo** [comment]
I probably changed few lines in code of the extension to make it compiled successfuly.

**Comment by flip111** [comment]
Microsoft released code for newer versions of php by now. Only 32 bits though

**Comment by maryo** [comment]
Good to know. So I've replaced the dlls with the official ones.
