### ISSUE TITLE
64bit

### ISSUE THREAD

**Issue by flip111** [maryo/php-5.5-windows-extensions#5]
The 64bits versions of the extensions are not available.

**Comment by ThaDafinser** [comment]
@flip111 check https://pecl.php.net/ there are build of nearly all extensions in all versions

**Comment by devinterx** [comment]
@ThaDafinser Lua for windows example? :-)

**Comment by ThaDafinser** [comment]
@devinterx bad example, but the common ones: http://windows.php.net/downloads/pecl/

**Comment by flip111** [comment]
I think he meant it as a challange to pecl .. to say not all extensions are there. I think originally i opened this PR after searching on PECL for some extension (but i don't remember which one it was).

I know automating the compilation is the most work .. so i guess if you have this setup then 64bits would be a small addition to add?
