### ISSUE TITLE
PHP Paradox Version

### ISSUE THREAD

**Issue by whitesn** [maryo/php-5.5-windows-extensions#6]
Excuse me, is this .dll compiled from https://pecl.php.net/package/paradox version 1.4.3? Most of the write functions are not available ("PECL paradox >= 1.4.0"), such as px_insert_record(), px_retrieve_record(), px_update_record(), etc. which can be seen here: http://php.net/manual/en/book.paradox.php

Which pxlib and iconv did you use to compile the paradox extension? I am trying to get the library working on windows with the writing functions enabled.

**Comment by maryo** [comment]
I am not sure, the PC I used to compile all extensions crashed. But I was trying to compile them using the newest libraries available in that time in case it was possible. So I guess it was compiled using
https://pecl.php.net/package/Paradox 1.4.3 stable, libiconv-1.14 and pxlib-0.6.5 but I am not sure. I guess it's not visible in phpinfo since you ask. I haven't used this extension so I probably didn't notice the missing functions. Feel free to send a PR if you compiled it with the writing functions enabled :).

**Comment by whitesn** [comment]
The doc said 1.4.0 above would have those functions I stated above though. Are you sure you compiled 1.4.3 ver? I would really love to share if I can compile the source myself, but there are so many old dependencies and I am not sure where to start honestly. Do you mind giving further hint or lead in case you have one? May I add you on messenger / other means of communication (IRC / Skype / etc.)

**Comment by maryo** [comment]
I'm not sure, but i think so.

I'd start with trying to build PHP using these steps:
https://wiki.php.net/internals/windows/stepbystepbuild

Then you'll have to copy the source of the extension from pecl to appropriate directory and again execute
`buildconf`
`configure --help` you should see the option for building paradox (if it's not there, there you've chosen a wrong directory or you haven't executed buildconf before)
`configure ...` with the same options you've built php but also `--with-paradox=shared`

If you spot "paradox not enabled; libraries and headers not found" then it's time to build pxlib.lib using sources from http://pxlib.sourceforge.net/ and
http://www.cmake.org/ tool

I don't remember exactly the steps here
Cmake has also an option to create a Visual Studio workspace so you can use it too if you are more familiar with GUI.
If more libraries are missing you'll need to build them too or find them already built somewhere
When you are done with building pxlib, place it's `.lib` and maybe some `.h` files to aproppriate directories in PHP source tree

execute `nmake` and then if it's succesfully built then you should find your shared dll somewhere.

Pray and never lose your faith during the process :)

**Comment by whitesn** [comment]
I have attempted and still trying to compile it, I got as far as getting compile error when running `nmake` with `--with-paradox=shared`

Error Messages: http://pastebin.com/Gp3J5yrL

**Comment by maryo** [comment]
Looks like the extension is written for an old version of PHP, probably 5.2. I had to change something when i was compiling it then.

You can try to replace "`function_entry` paradox_functions" and similar with `zend_function_entry`. 

But there's also `pecl\paradox\paradox.c(154) : fatal error C1083: Cannot open include file: 'zend
_arg_defs.c': No such file or directory`

You can try to comment it out or find something on google, like this one.
https://code.google.com/p/php52-backports/source/browse/trunk/Zend/zend_arg_defs.c?r=30

As you can see, maybe that's the reason why it's not working properly :).

**Comment by whitesn** [comment]
ok, so I managed to compiled the php_paradox successfully but it seems I got the same problem. Which might be caused by 

``` C
#ifdef HAVE_PXRETRIEVERECORD
PHP_FUNCTION(px_retrieve_record);
#endif
```

~~I will try to work around first, but thanks for the help though <3~~

omg it works, thanks for your help. I don't mind sharing the dll, but I think what I did was some kind of hack instead of the normal procedure since I'm not really fond of this.

**Comment by maryo** [comment]
I haven't noticed your update of the last post.  I guess you either defined the constant or removed the entire condition. It could be ok if it works. Closing the issue. Someone may appreciate if you sent a PR or a link to the dll.

**Comment by whitesn** [comment]
I'll just leave this here: http://whitesn.net/upload/php_paradox.dll

Warning: This is successfully compiled by removing conditions in the source, which might trigger errors / problems, use it at your own risk.

**Comment by masteraxe** [comment]
Hello whitesn:
In which directory do you place the pxlib.dll and other files that maryo has compiled and that are available on sourceforge?
Please help.
Anil

**Comment by whitesn** [comment]
@masteraxe php/extensions/\* and add it to php.ini (extension="pxlib.dll"), if you want to compile. If you just want to use the paradox library, just download one that I uploaded.

**Comment by masteraxe** [comment]
Thanks for the reply. What build did you compile this on: vc##, -86 or -64. I am assuming that the php version is 5.5. I am still confused between php_paradox.dll and pxlib.dll. The pxlib.dll is the compiled c++ library and php_paradox.dll is the php wrapper over it. Is this correct? If yes, then extension=pxlib.dll should not work. Or are they the same with a different name. 
I have built php5.4 on windows xp as per the instructions on php.net. I will next compile with the paradox extension. The instructions say that we have to make sure that pxlib is installed.

*******\* from installation instructions
" Information for installing this PECL extension may be found in the manual chapter titled Installation of PECL extensions. Additional information such as new releases, downloads, source files, maintainer information, and a CHANGELOG, can be located here: » http://pecl.php.net/package/paradox

Make sure you have pxlib installed before. If you install pxlib from an rpm or debian package, do not forget to install the development package as well"  <--- Here is where I get confused. Perhaps you or Maryo can help.
Thanks, Anil

**Comment by maryo** [comment]
"Is this correct?" Yes. You should `extension=php_paradox.dll` and have the pxlib somewhere PHP can use it. I'd copy `php_paradox.dll` to extensions dir and `pxlib.dll` to PHP root directory.

I don't use 5.5 anymore but I can replace the dll with the one @whitesn provided if someone confirms it works well. Is it TS or NTS version?

**Comment by whitesn** [comment]
IIRC it was NTS @maryo , but I don't quite remember since this was long time ago. There were little to no support during the time I am trying to compile this.

**Comment by Adel-Qusay** [comment]
@whitesn Please i need your -Updated- php_paradox.dll for php 5.5 
This link is broken http://whitesn.net/upload/php_paradox.dll
Thanks
