### ISSUE TITLE
Encrypt files using gnupg with php iis server?

### ISSUE THREAD

**Issue by tayyem** [maryo/php-5.5-windows-extensions#7]
I've faced the error

Warning: gnupg_import(): import failed " while importing the public key and I did not have any luck solving this issue , when use (iis server-win8) with (php-5.5-windows-extensions/php_gnupg-1.3.3-5.5-vc11-x86/).
The question is, can i use php_gnupg (PGP (Pretty Good Privacy)) with IIS server to encrypted file ?

php_gnupg is a compatible with iis server !

NOTE:

This problem does not appear when use XAMPP sever

**Comment by maryo** [comment]
Thanks fo reporting but I don't have the build environment anymore as well as I don't use 5.5 and IIS so I won't try to test/rebuild it.
