### ISSUE TITLE
GraphicsMagick-1.4.02-Q16.7z  bug in system windows10

### ISSUE THREAD

**Issue by xjpphp** [maryo/php-5.5-windows-extensions#8]
GraphicsMagick-1.4.02-Q16.7z  bug in system windows10 : Fatal error: Uncaught exception 'GmagickException' with message 'Unable to access configuration file (delegates.mgk)'

**Comment by maryo** [comment]
That's not Windows10 specific. I forgot to mention it anywhere. You have to set `MAGICK_HOME` environment variable to a folder where the `delegates.mgk` lives. The same for ImageMagick. I've uploaded README.md - https://github.com/maryo/php-5.5-windows-extensions/blob/master/php_gmagick-1.1.6RC2-5.5-vc11-x86/README.md
